name: vercel-deploy
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [ main ]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js ${{ matrix.node-version }} and install vercel CLI
      uses: actions/setup-node@v3.8.2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global vercel@latest
    - name: Deploy Project Vercel
      run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}